### ISSUE TITLE
タスク 3‐1 で使用する App ID 

### ISSUE THREAD

**Issue by horihiro** [osamum/Easyway-for-MSTeamsAppDev#4]
[タスク 3-1 : 外部の HTML フォームをタスクモジュールとしてタブに追加](https://github.com/osamum/Easyway-for-MSTeamsAppDev/blob/update2021March/Ex02.md#%E3%82%BF%E3%82%B9%E3%82%AF-3-1--%E5%A4%96%E9%83%A8%E3%81%AE-html-%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0%E3%82%92%E3%82%BF%E3%82%B9%E3%82%AF%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%81%97%E3%81%A6%E3%82%BF%E3%83%96%E3%81%AB%E8%BF%BD%E5%8A%A0) の `検証用 Teams アプリの App ID (GUID)` は [Ex01 で自動生成](https://github.com/osamum/Easyway-for-MSTeamsAppDev/blob/update2021March/Ex01.md#identification)したもの？

> 4. 貼り付けたページ内の script タグ内の microsoftTeams.tasks.submitTask メソッド の第二引数にセットされている文字列 'ここに Teams アプリのApp IDを記述' を検証用 Teams アプリの App ID (GUID) で置き換えます。

**Comment by osamum** [comment]
そのとおりです。
後半にすると Azure Active Directory で生成した ID と紛らわしくなるので、ご質問いただいた点、追記しておきますね。
