### ISSUE TITLE
Teams のサイド ローディング設定

### ISSUE THREAD

**Issue by horihiro** [osamum/Easyway-for-MSTeamsAppDev#5]
Microsoft Teams 管理センターでサイドローディングの許可

```
具体的には Microsoft Teams 管理センターのメニュー[Teams のアプリ] - [セットアップ ポリシー] で 「カスタム アプリのアップロードを許可」をオンにします。
```

自分の環境では、「カスタム アプリのアップロードを許可」の設定前に、`Global` というポリシーを選ばないといけなかった。

また、設定変更後に `Save` クリックが必要。

**Comment by osamum** [comment]
確認しました。
たしかにポリシーで「グローバル (組織全体の既定値)」と「FirstLineWorker」が出てきますね。
初めて見ました (追加されたんですかね?)
追記しておきますね。
ご報告ありがとうございました。
